import type { Metadata } from "next";
import '@stream-io/video-react-sdk/dist/css/styles.css';
import "react-datepicker/dist/react-datepicker.css";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { MeetingModalProvider } from "@/providers/MeetingModalContext";
import ToastProvider from "@/providers/ToastProvider";
import { FormProvider } from "@/providers/FormProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          socialButtonsVariant: "iconButton",
          logoImageUrl: "/icons/yoom-logo.svg",
        },
        variables: {
          colorText: "#fff",
          colorPrimary: "#0E78F9",
          colorBackground: "#1C1F2E",
          colorInputBackground: "#252A41",
          colorInputText: "#fff",
        },
      }}
    >
      <MeetingModalProvider>
        <ToastProvider>
          <FormProvider>
            <html lang="en">
              <body className="bg-[#161925]">{children}</body>
            </html>
          </FormProvider>
        </ToastProvider>
      </MeetingModalProvider>
    </ClerkProvider>
  );
}
